import { PageHeader } from "@/components/PageHeader";
import { trpc } from "@/lib/trpc";
import { AlertCircle, CheckCircle2, Database, FileSpreadsheet, FileUp, Loader2, ShieldCheck } from "lucide-react";
import { useRef, useState } from "react";
import { toast } from "sonner";

function toBase64(file: File) {
  return new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(String(reader.result).split(",")[1] || "");
    reader.onerror = () => reject(new Error("Não foi possível ler o ficheiro."));
    reader.readAsDataURL(file);
  });
}

type Profile = { fileName: string; profile: { rowCount: number; columnCount: number; duplicateRowCount: number; missingValueCount: number; qualityScore: number; suggestedMetrics: string[]; columns: Array<{ name: string; inferredType: string; completeness: number; distinctCount: number }> } };

export default function DataCenter() {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [profile, setProfile] = useState<Profile | null>(null);
  const utils = trpc.useUtils();
  const importsQuery = trpc.data.listImports.useQuery();
  const importMutation = trpc.data.importFile.useMutation({
    onSuccess: (result) => { setProfile({ fileName: result.fileName, profile: result.profile }); utils.data.listImports.invalidate(); toast.success(result.metricSnapshotsCreated ? `${result.metricSnapshotsCreated} período(s) preparados para análise.` : "Fonte analisada e guardada."); },
    onError: (error) => toast.error(error.message),
  });
  const handleFile = async (file?: File) => {
    if (!file) return;
    if (file.size > 8 * 1024 * 1024) { toast.error("Envie um ficheiro de até 8 MB."); return; }
    try { importMutation.mutate({ fileName: file.name, contentType: file.type || "application/octet-stream", contentBase64: await toBase64(file) }); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível preparar o ficheiro."); }
  };

  return <div className="space-y-7 pb-6">
    <PageHeader eyebrow="Dados e importações" title="Ligue os dados que ajudam a gerir o negócio." description="Envie uma folha de cálculo ou ficheiro de vendas. A Quantico identifica a estrutura e prepara os indicadores de receita, vendas e clientes." />
    <section className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_340px]">
      <article className="quantico-card p-5 sm:p-6"><div><p className="text-xs font-medium text-[#5d6875]">1. Escolha o ficheiro</p><h2 className="mt-2 text-xl font-bold tracking-[-0.04em] text-[#242424]">Importe vendas, clientes ou receitas.</h2><p className="mt-2 text-sm leading-6 text-[#5f6872]">Aceitamos CSV, XLSX e JSON. O ficheiro é analisado apenas no workspace da sua organização.</p></div><button onClick={() => fileInputRef.current?.click()} disabled={importMutation.isPending} className="mt-7 flex min-h-48 w-full flex-col items-center justify-center rounded-md border border-dashed border-[#aab7c4] bg-[#fbfcfd] px-5 text-center transition-colors hover:border-[#0b62b4] hover:bg-[#f2f7fc] disabled:opacity-70"><span className="flex size-11 items-center justify-center rounded-md bg-[#eaf3fc] text-[#0b62b4]">{importMutation.isPending ? <Loader2 className="size-5 animate-spin" /> : <FileUp className="size-5" />}</span><span className="mt-4 text-sm font-semibold text-[#242424]">{importMutation.isPending ? "A analisar o ficheiro…" : "Escolher CSV, XLSX ou JSON"}</span><span className="mt-1.5 text-xs text-[#687785]">Até 8 MB. Não guardamos dados no navegador.</span></button><input ref={fileInputRef} type="file" accept=".csv,.xlsx,.xls,.json,text/csv,application/json,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" className="hidden" onChange={(event) => handleFile(event.target.files?.[0])} /></article>
      <aside className="quantico-card p-5 sm:p-6"><div className="flex size-10 items-center justify-center rounded-md bg-[#eaf3fc] text-[#0b62b4]"><ShieldCheck className="size-[19px]" /></div><h2 className="mt-5 text-base font-semibold tracking-[-0.03em] text-[#242424]">Dados organizados e protegidos</h2><p className="mt-2 text-sm leading-6 text-[#5f6872]">Cada ficheiro pertence à sua organização. Apenas as métricas agregadas autorizadas chegam aos painéis e à análise por IA.</p><div className="mt-6 border-t border-[#e4e8ec] pt-5"><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[#60748a]">Em breve</p><div className="mt-3 flex flex-wrap gap-2">{["PostgreSQL", "MySQL", "Google Sheets", "API"].map((item) => <span key={item} className="rounded-md bg-[#f1f5f8] px-2.5 py-1 text-[10px] font-medium text-[#506273]">{item}</span>)}</div></div></aside>
    </section>
    {profile ? <section className="quantico-card overflow-hidden"><div className="flex flex-col gap-3 border-b border-[#e4e8ec] px-5 py-5 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-md bg-[#eaf3fc] text-[#0b62b4]"><CheckCircle2 className="size-[18px]" /></div><div><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[#60748a]">Ficheiro analisado</p><h2 className="mt-0.5 text-base font-semibold tracking-[-0.03em] text-[#242424]">{profile.fileName}</h2></div></div><div className="rounded-md bg-[#edf5fd] px-3 py-1.5 text-xs font-semibold text-[#0b62b4]">Qualidade dos dados: {profile.profile.qualityScore}%</div></div><div className="grid gap-3 p-5 sm:grid-cols-4"><Stat label="Linhas encontradas" value={profile.profile.rowCount.toLocaleString("pt-AO")} /><Stat label="Colunas identificadas" value={profile.profile.columnCount.toString()} /><Stat label="Campos em falta" value={profile.profile.missingValueCount.toLocaleString("pt-AO")} /><Stat label="Linhas repetidas" value={profile.profile.duplicateRowCount.toLocaleString("pt-AO")} /></div><div className="grid gap-5 border-t border-[#e4e8ec] p-5 xl:grid-cols-[minmax(0,1fr)_320px]"><div className="overflow-x-auto"><table className="w-full min-w-[500px] text-left"><thead><tr className="text-[10px] font-semibold uppercase tracking-[0.1em] text-[#60748a]"><th className="pb-3">Coluna</th><th className="pb-3">Tipo</th><th className="pb-3">Preenchimento</th><th className="pb-3 text-right">Valores diferentes</th></tr></thead><tbody>{profile.profile.columns.map((column) => <tr key={column.name} className="border-t border-[#edf0f2]"><td className="py-3 text-sm font-semibold text-[#303840]">{column.name}</td><td className="py-3"><span className="rounded-md bg-[#f1f5f8] px-2 py-1 font-mono text-[10px] text-[#526271]">{column.inferredType}</span></td><td className="py-3"><div className="flex items-center gap-2"><div className="h-1.5 w-20 overflow-hidden rounded-full bg-[#e9eef3]"><div className="h-full rounded-full bg-[#0b62b4]" style={{ width: `${column.completeness}%` }} /></div><span className="text-xs text-[#5e6c79]">{column.completeness}%</span></div></td><td className="py-3 text-right text-sm text-[#53616e]">{column.distinctCount.toLocaleString("pt-AO")}</td></tr>)}</tbody></table></div><div className="rounded-md bg-[#edf5fd] p-4"><p className="text-[10px] font-semibold uppercase tracking-[0.1em] text-[#0b62b4]">Indicadores que podemos criar</p><div className="mt-3 space-y-2">{profile.profile.suggestedMetrics.length ? profile.profile.suggestedMetrics.map((metric) => <p key={metric} className="text-sm font-semibold leading-5 text-[#244b70]">{metric}</p>) : <p className="text-sm leading-5 text-[#526f89]">Inclua data, valor de venda ou cliente para receber sugestões específicas.</p>}</div></div></div></section> : null}
    <section className="quantico-card overflow-hidden"><div className="flex items-center justify-between border-b border-[#e4e8ec] px-5 py-5 sm:px-6"><div><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[#60748a]">Ficheiros importados</p><h2 className="mt-1 text-lg font-bold tracking-[-0.04em] text-[#242424]">Os seus dados</h2></div><Database className="size-5 text-[#0b62b4]" /></div>{importsQuery.isLoading ? <div className="flex items-center gap-2 p-6 text-sm text-[#5f6872]"><Loader2 className="size-4 animate-spin" />A carregar ficheiros…</div> : importsQuery.data?.length ? <div className="divide-y divide-[#edf0f2]">{importsQuery.data.map((item) => <div key={item.id} className="flex items-center gap-3 px-5 py-4 sm:px-6"><div className="flex size-9 items-center justify-center rounded-md bg-[#f1f5f8] text-[#506d87]"><FileSpreadsheet className="size-[18px]" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-[#303840]">{item.fileName}</p><p className="mt-0.5 text-xs text-[#667583]">{item.rowCount.toLocaleString("pt-AO")} linhas · qualidade {item.qualityScore}%</p></div><span className="hidden rounded-md bg-[#edf5fd] px-2.5 py-1 text-[10px] font-semibold text-[#0b62b4] sm:inline">Pronto para análise</span></div>)}</div> : <div className="flex items-center gap-3 p-6 text-sm text-[#5f6872]"><AlertCircle className="size-4 text-[#0b62b4]" />Ainda não importou nenhum ficheiro.</div>}</section>
  </div>;
}

function Stat({ label, value }: { label: string; value: string }) { return <div className="rounded-md bg-[#f7f9fb] p-4"><p className="text-[10px] font-semibold uppercase tracking-[0.1em] text-[#60748a]">{label}</p><p className="mt-2 text-xl font-bold tracking-[-0.04em] text-[#242424]">{value}</p></div>; }
