import { PageHeader } from "@/components/PageHeader";
import { Area, AreaChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Activity, BadgeCheck, CircleAlert } from "lucide-react";

const forecastData = [
  { month: "Abr", actual: 34.8, expected: null, optimistic: null, pessimistic: null },
  { month: "Mai", actual: 36.6, expected: null, optimistic: null, pessimistic: null },
  { month: "Jun", actual: 38.1, expected: null, optimistic: null, pessimistic: null },
  { month: "Jul", actual: 41.5, expected: null, optimistic: null, pessimistic: null },
  { month: "Ago", actual: 48.2, expected: 48.2, optimistic: 48.2, pessimistic: 48.2 },
  { month: "Set", actual: null, expected: 53, optimistic: 56.5, pessimistic: 48.6 },
  { month: "Out", actual: null, expected: 57, optimistic: 62, pessimistic: 50.2 },
  { month: "Nov", actual: null, expected: 60.8, optimistic: 67.2, pessimistic: 51.9 },
];

const tooltipStyle = { borderRadius: "14px", border: "1px solid #e1e8e8", boxShadow: "0 12px 24px rgba(24, 35, 35, 0.08)", fontSize: "12px" };

export default function Forecasting() {
  return <div className="space-y-7 pb-6"><PageHeader eyebrow="Previsão de vendas" title="Antecipe quanto pode vender nos próximos meses." description="Compare o que já vendeu com a estimativa de vendas para planear a equipa, as compras e as próximas ações." />
    <section className="grid gap-3 sm:grid-cols-3"><article className="quantico-card p-5"><div className="flex items-center justify-between"><p className="text-xs font-semibold text-[#54718e]">Estimativa para setembro</p><BadgeCheck className="size-4 text-[#176eae]" /></div><p className="mt-4 text-[29px] font-extrabold tracking-[-0.065em] text-[#102a43]">53,0M Kz</p><p className="mt-2 text-xs font-semibold text-[#176eae]">9,9% acima de agosto</p></article><article className="quantico-card p-5"><div className="flex items-center justify-between"><p className="text-xs font-semibold text-[#54718e]">Faixa provável</p><Activity className="size-4 text-[#176eae]" /></div><p className="mt-4 text-[29px] font-extrabold tracking-[-0.065em] text-[#102a43]">48,6–56,5M</p><p className="mt-2 text-xs font-semibold text-[#54718e]">Confiança média-alta: 78%</p></article><article className="quantico-card p-5"><div className="flex items-center justify-between"><p className="text-xs font-semibold text-[#54718e]">O que mais pode mudar o resultado</p><CircleAlert className="size-4 text-[#176eae]" /></div><p className="mt-4 text-[29px] font-extrabold tracking-[-0.065em] text-[#102a43]">Canal direto</p><p className="mt-2 text-xs font-semibold text-[#176eae]">Pode explicar 31% da variação</p></article></section>
    <article className="quantico-card p-5 sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold text-[#54718e]">Vendas já realizadas e previsão</p><h2 className="mt-2 text-xl font-extrabold tracking-[-0.05em] text-[#102a43]">A previsão ajuda a planear o próximo mês.</h2><p className="mt-2 text-xs leading-5 text-[#688099]">Linha cheia: vendas realizadas. Linha tracejada: valor esperado. Linhas finas: melhor e pior cenário.</p></div><div className="flex gap-3 text-[10px] font-semibold text-[#54718e]"><span className="inline-flex items-center gap-1.5"><span className="size-2 rounded-full bg-[#0f69b3]" />Realizado</span><span className="inline-flex items-center gap-1.5"><span className="size-2 rounded-full bg-[#4b95d1]" />Esperado</span><span className="inline-flex items-center gap-1.5"><span className="size-2 rounded-full bg-[#a4cbea]" />Intervalo</span></div></div><div className="mt-6 h-[330px]"><ResponsiveContainer width="100%" height="100%" minWidth={0} minHeight={300}><LineChart data={forecastData} margin={{ top: 8, right: 8, left: -20, bottom: 0 }}><CartesianGrid vertical={false} stroke="#e4eff9" strokeDasharray="4 4" /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: "#6682a0", fontSize: 11 }} dy={10} /><YAxis axisLine={false} tickLine={false} tick={{ fill: "#6682a0", fontSize: 11 }} tickFormatter={(value) => `${value}M`} /><Tooltip contentStyle={tooltipStyle} formatter={(value: number) => [`${value.toFixed(1)}M Kz`]} /><Line type="monotone" dataKey="actual" name="Realizado" stroke="#0f69b3" strokeWidth={2.8} dot={{ r: 3, fill: "#0f69b3" }} connectNulls={false} /><Line type="monotone" dataKey="expected" name="Esperado" stroke="#4b95d1" strokeWidth={2.8} strokeDasharray="5 4" dot={{ r: 3, fill: "#4b95d1" }} /><Line type="monotone" dataKey="optimistic" name="Melhor cenário" stroke="#a4cbea" strokeWidth={1.5} strokeDasharray="3 5" dot={false} /><Line type="monotone" dataKey="pessimistic" name="Pior cenário" stroke="#a4cbea" strokeWidth={1.5} strokeDasharray="3 5" dot={false} /></LineChart></ResponsiveContainer></div></article>
    <section className="grid gap-5 xl:grid-cols-2"><article className="quantico-card p-5 sm:p-6"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#54799e]">O que pode ajudar as vendas</p><div className="mt-5 space-y-4"><div className="flex gap-3"><span className="mt-1 size-2 shrink-0 rounded-full bg-[#5f9ed6]" /><div><p className="text-sm font-bold text-[#183b5d]">Mais negócios estão a chegar à proposta</p><p className="mt-1 text-sm leading-6 text-[#5f7890]">18 oportunidades com valor superior a 500 mil Kz podem chegar à fase de proposta neste ciclo.</p></div></div><div className="flex gap-3"><span className="mt-1 size-2 shrink-0 rounded-full bg-[#5f9ed6]" /><div><p className="text-sm font-bold text-[#183b5d]">Clientes estão a comprar mais vezes</p><p className="mt-1 text-sm leading-6 text-[#5f7890]">Os clientes ativos aumentaram o valor médio comprado em três grupos importantes.</p></div></div></div></article><article className="quantico-card p-5 sm:p-6"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#54799e]">O que precisa de atenção</p><div className="mt-5 space-y-4"><div className="flex gap-3"><span className="mt-1 size-2 shrink-0 rounded-full bg-[#8bbfe6]" /><div><p className="text-sm font-bold text-[#183b5d]">Propostas demoram a ser aprovadas</p><p className="mt-1 text-sm leading-6 text-[#5f7890]">Propostas paradas mais de sete dias podem reduzir a estimativa em até 3,4M Kz.</p></div></div><div className="flex gap-3"><span className="mt-1 size-2 shrink-0 rounded-full bg-[#8bbfe6]" /><div><p className="text-sm font-bold text-[#183b5d]">Clientes VIP estão a comprar menos vezes</p><p className="mt-1 text-sm leading-6 text-[#5f7890]">Contactar estes clientes primeiro ajuda a manter a previsão de vendas em linha com o esperado.</p></div></div></div></article></section>
  </div>;
}
