import { PageHeader } from "@/components/PageHeader";
import { Area, AreaChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Activity, BadgeCheck, CircleAlert } from "lucide-react";

const forecastData = [
  { month: "Abr", actual: 34.8, expected: null, optimistic: null, pessimistic: null },
  { month: "Mai", actual: 36.6, expected: null, optimistic: null, pessimistic: null },
  { month: "Jun", actual: 38.1, expected: null, optimistic: null, pessimistic: null },
  { month: "Jul", actual: 41.5, expected: null, optimistic: null, pessimistic: null },
  { month: "Ago", actual: 48.2, expected: 48.2, optimistic: 48.2, pessimistic: 48.2 },
  { month: "Set", actual: null, expected: 53, optimistic: 56.5, pessimistic: 48.6 },
  { month: "Out", actual: null, expected: 57, optimistic: 62, pessimistic: 50.2 },
  { month: "Nov", actual: null, expected: 60.8, optimistic: 67.2, pessimistic: 51.9 },
];

const tooltipStyle = { borderRadius: "14px", border: "1px solid #e1e8e8", boxShadow: "0 12px 24px rgba(24, 35, 35, 0.08)", fontSize: "12px" };

export default function Forecasting() {
  return <div className="space-y-7 pb-6"><PageHeader eyebrow="Previsão comercial" title="Antecipe os próximos movimentos da receita." description="Compare tendência, cenários e margem de confiança para orientar decisões antes do fechamento do ciclo." />
    <section className="grid gap-3 sm:grid-cols-3"><article className="quantico-card p-5"><div className="flex items-center justify-between"><p className="text-xs font-medium text-[#6d7b7c]">Cenário esperado · Setembro</p><BadgeCheck className="size-4 text-[#4d836f]" /></div><p className="mt-4 text-[29px] font-extrabold tracking-[-0.065em] text-[#172122]">53,0M Kz</p><p className="mt-2 text-xs font-semibold text-[#4d836f]">+9,9% vs. agosto</p></article><article className="quantico-card p-5"><div className="flex items-center justify-between"><p className="text-xs font-medium text-[#6d7b7c]">Intervalo de confiança</p><Activity className="size-4 text-[#467fb8]" /></div><p className="mt-4 text-[29px] font-extrabold tracking-[-0.065em] text-[#172122]">48,6–56,5M</p><p className="mt-2 text-xs font-semibold text-[#6381a0]">Médio-alto · 78%</p></article><article className="quantico-card p-5"><div className="flex items-center justify-between"><p className="text-xs font-medium text-[#6d7b7c]">Maior variável</p><CircleAlert className="size-4 text-[#a66170]" /></div><p className="mt-4 text-[29px] font-extrabold tracking-[-0.065em] text-[#172122]">Canal direto</p><p className="mt-2 text-xs font-semibold text-[#a66170]">31% do desvio potencial</p></article></section>
    <article className="quantico-card p-5 sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-medium text-[#6d7b7c]">Receita realizada e projeção</p><h2 className="mt-2 text-xl font-extrabold tracking-[-0.05em] text-[#172122]">Crescimento esperado mantém-se acima do plano.</h2></div><div className="flex gap-3 text-[10px] font-semibold text-[#748284]"><span className="inline-flex items-center gap-1.5"><span className="size-2 rounded-full bg-[#4e88c2]" />Real</span><span className="inline-flex items-center gap-1.5"><span className="size-2 rounded-full bg-[#93c1af]" />Esperado</span><span className="inline-flex items-center gap-1.5"><span className="size-2 rounded-full bg-[#e5afba]" />Intervalo</span></div></div><div className="mt-6 h-[330px]"><ResponsiveContainer width="100%" height="100%" minWidth={0} minHeight={300}><LineChart data={forecastData} margin={{ top: 8, right: 8, left: -20, bottom: 0 }}><CartesianGrid vertical={false} stroke="#e8eeee" strokeDasharray="4 4" /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: "#819092", fontSize: 11 }} dy={10} /><YAxis axisLine={false} tickLine={false} tick={{ fill: "#819092", fontSize: 11 }} tickFormatter={(value) => `${value}M`} /><Tooltip contentStyle={tooltipStyle} formatter={(value: number) => [`${value.toFixed(1)}M Kz`]} /><Line type="monotone" dataKey="actual" name="Real" stroke="#4e88c2" strokeWidth={2.8} dot={{ r: 3, fill: "#4e88c2" }} connectNulls={false} /><Line type="monotone" dataKey="expected" name="Esperado" stroke="#75a991" strokeWidth={2.8} strokeDasharray="5 4" dot={{ r: 3, fill: "#75a991" }} /><Line type="monotone" dataKey="optimistic" name="Otimista" stroke="#d99eac" strokeWidth={1.2} strokeDasharray="3 5" dot={false} /><Line type="monotone" dataKey="pessimistic" name="Pessimista" stroke="#d99eac" strokeWidth={1.2} strokeDasharray="3 5" dot={false} /></LineChart></ResponsiveContainer></div></article>
    <section className="grid gap-5 xl:grid-cols-2"><article className="quantico-card p-5 sm:p-6"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#849193]">Drivers positivos</p><div className="mt-5 space-y-4"><div className="flex gap-3"><span className="mt-1 size-2 shrink-0 rounded-full bg-[#8fc2ac]" /><div><p className="text-sm font-bold text-[#293536]">Pipeline enterprise em maturação</p><p className="mt-1 text-sm leading-6 text-[#6b797a]">18 oportunidades com valor superior a 500 mil Kz alcançam fase de proposta neste ciclo.</p></div></div><div className="flex gap-3"><span className="mt-1 size-2 shrink-0 rounded-full bg-[#8fc2ac]" /><div><p className="text-sm font-bold text-[#293536]">Recorrência acima da tendência</p><p className="mt-1 text-sm leading-6 text-[#6b797a]">A base ativa apresenta crescimento de ticket em três segmentos de maior margem.</p></div></div></div></article><article className="quantico-card p-5 sm:p-6"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#849193]">Riscos a monitorizar</p><div className="mt-5 space-y-4"><div className="flex gap-3"><span className="mt-1 size-2 shrink-0 rounded-full bg-[#e2a4b2]" /><div><p className="text-sm font-bold text-[#293536]">Aprovação de propostas maduras</p><p className="mt-1 text-sm leading-6 text-[#6b797a]">Atrasos acima de sete dias nas propostas podem reduzir o cenário esperado em até 3,4M Kz.</p></div></div><div className="flex gap-3"><span className="mt-1 size-2 shrink-0 rounded-full bg-[#e2a4b2]" /><div><p className="text-sm font-bold text-[#293536]">Queda de frequência de contas VIP</p><p className="mt-1 text-sm leading-6 text-[#6b797a]">A reativação prioritária das contas em risco reduz a pressão sobre o cenário pessimista.</p></div></div></div></article></section>
  </div>;
}
