import { PageHeader } from "@/components/PageHeader";
import { ArrowUpRight, Boxes, CircleDollarSign, RefreshCcw, UserRoundPlus } from "lucide-react";
import { useLocation } from "wouter";

type OpportunityTone = "blush" | "blue" | "mint";

const opportunities: Array<{ index: string; type: string; title: string; description: string; potential: string; confidence: string; icon: typeof RefreshCcw; tone: OpportunityTone }> = [
  { index: "01", type: "Retenção", title: "Recuperar clientes inativos", description: "234 clientes não compram há mais de 60 dias. A reativação orientada por valor e categoria pode recuperar receita de curto prazo.", potential: "12,4M Kz", confidence: "Alta confiança", icon: RefreshCcw, tone: "blush" },
  { index: "02", type: "Cross-sell", title: "Criar oferta combinada A + B", description: "34% dos clientes do Produto A ainda não adquiriram o Produto B, apesar de uma afinidade histórica de 68%.", potential: "6,8M Kz", confidence: "Média-alta", icon: Boxes, tone: "blue" },
  { index: "03", type: "Expansão", title: "Acelerar contas Potential VIP", description: "312 clientes crescem acima da média e ainda não atingiram o seu potencial de categoria ou cobertura comercial.", potential: "5,1M Kz", confidence: "Média confiança", icon: UserRoundPlus, tone: "mint" },
];

const toneStyle: Record<OpportunityTone, string> = { blush: "bg-[#f8e2e7] text-[#9d5869]", blue: "bg-[#dbeafe] text-[#3a75ad]", mint: "bg-[#dfeee9] text-[#4b806d]" };

export default function GrowthOpportunities() {
  const [, setLocation] = useLocation();
  return <div className="space-y-7 pb-6"><PageHeader eyebrow="Revenue Intelligence" title="Transforme sinais em oportunidades de crescimento." description="Uma lista priorizada de movimentos comerciais com potencial estimado, evidência e próxima ação recomendada." />
    <section className="grid gap-4 xl:grid-cols-3">{opportunities.map((opportunity) => { const Icon = opportunity.icon; return <article key={opportunity.index} className="quantico-card group flex min-h-[330px] flex-col p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div className={`flex size-11 items-center justify-center rounded-xl ${toneStyle[opportunity.tone]}`}><Icon className="size-5" /></div><span className="font-mono text-xs text-[#889697]">{opportunity.index}</span></div><p className="mt-7 text-[10px] font-bold uppercase tracking-[0.14em] text-[#839092]">{opportunity.type}</p><h2 className="mt-2 text-xl font-extrabold leading-tight tracking-[-0.055em] text-[#192526]">{opportunity.title}</h2><p className="mt-3 text-sm leading-6 text-[#697779]">{opportunity.description}</p><div className="mt-auto flex items-end justify-between gap-3 border-t border-[#e6ecec] pt-5"><div><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-[#899698]">Potencial estimado</p><p className="mt-1 text-lg font-extrabold tracking-[-0.05em] text-[#253233]">{opportunity.potential}</p><p className="mt-0.5 text-[10px] font-semibold text-[#52816f]">{opportunity.confidence}</p></div><button onClick={() => setLocation("/ask-quantico")} className="flex size-9 items-center justify-center rounded-lg bg-[#172122] text-white transition-transform duration-200 hover:-translate-y-0.5"><ArrowUpRight className="size-4" /></button></div></article>})}</section>
    <section className="relative overflow-hidden rounded-[22px] bg-[#172122] px-6 py-7 text-white sm:px-8"><div className="absolute -right-12 -top-20 size-56 rounded-full bg-[#dbeafe] opacity-25" /><div className="relative flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-[#a8cbef]">Impacto combinado identificado</p><p className="mt-2 text-3xl font-extrabold tracking-[-0.065em]">24,3M Kz</p><p className="mt-2 max-w-xl text-sm leading-6 text-[#b7c4c5]">Potencial estimado das três oportunidades prioritárias, sujeito à validação das fontes conectadas e ao desenho da ação comercial.</p></div><button onClick={() => setLocation("/ask-quantico")} className="quantico-cta inline-flex shrink-0 items-center gap-2 rounded-xl bg-[#dbeafe] px-4 py-3 text-sm font-bold text-[#1d2b2d]"><CircleDollarSign className="size-4 text-[#3c78b2]" />Validar com Quantico AI</button></div></section>
  </div>;
}
