import { and, desc, eq } from "drizzle-orm";
import { actionFollowUps, growthActions } from "../drizzle/schema";
import { getDb } from "./db";

export const actionTypes = ["reactivation", "upsell", "cross_sell", "efficiency", "custom"] as const;
export const actionStatuses = ["draft", "active", "completed", "archived"] as const;
export type ActionType = (typeof actionTypes)[number];
export type ActionStatus = (typeof actionStatuses)[number];

export async function listGrowthActions(organizationId: number) { const db = await getDb(); return db ? db.select().from(growthActions).where(eq(growthActions.organizationId, organizationId)).orderBy(desc(growthActions.updatedAt)).limit(100) : []; }
export async function createGrowthAction(input: { organizationId: number; createdByUserId: number; title: string; actionType: ActionType; segment: string; estimatedRevenue: number; notes?: string; assigneeName?: string; sourceSignal?: string }) { const db = await getDb(); if (!db) throw new Error("A base de dados não está disponível para criar a acção."); const [created] = await db.insert(growthActions).values({ ...input, title: input.title.trim(), segment: input.segment.trim(), sourceSignal: input.sourceSignal?.trim() || null, assigneeName: input.assigneeName?.trim() || null, notes: input.notes?.trim() || null, estimatedRevenue: Math.max(0, Math.round(input.estimatedRevenue)), actualRevenue: 0, progress: 0, status: "draft" }).$returningId(); return { id: created?.id, ...input, status: "draft" as const }; }
export async function setGrowthActionStatus(input: { organizationId: number; actionId: number; status: ActionStatus }) { const db = await getDb(); if (!db) throw new Error("A base de dados não está disponível para actualizar a acção."); const result = await db.update(growthActions).set({ status: input.status, completedAt: input.status === "completed" ? new Date() : null }).where(and(eq(growthActions.id, input.actionId), eq(growthActions.organizationId, input.organizationId))); if (!result[0].affectedRows) throw new Error("Acção não encontrada nesta organização."); return { actionId: input.actionId, status: input.status }; }
export async function updateGrowthActionResult(input: { organizationId: number; actionId: number; progress: number; actualRevenue: number; resultNotes?: string; assigneeName?: string; status: ActionStatus }) { const db = await getDb(); if (!db) throw new Error("A base de dados não está disponível para actualizar o resultado."); const result = await db.update(growthActions).set({ progress: Math.max(0, Math.min(100, Math.round(input.progress))), actualRevenue: Math.max(0, Math.round(input.actualRevenue)), resultNotes: input.resultNotes?.trim() || null, assigneeName: input.assigneeName?.trim() || null, status: input.status, completedAt: input.status === "completed" ? new Date() : null }).where(and(eq(growthActions.id, input.actionId), eq(growthActions.organizationId, input.organizationId))); if (!result[0].affectedRows) throw new Error("Acção não encontrada nesta organização."); return { actionId: input.actionId, progress: input.progress, actualRevenue: input.actualRevenue, status: input.status }; }
export async function addActionFollowUp(input: { organizationId: number; actionId: number; createdByUserId: number; note: string; progress: number }) { const db = await getDb(); if (!db) throw new Error("A base de dados não está disponível para guardar o follow-up."); const action = (await db.select({ id: growthActions.id }).from(growthActions).where(and(eq(growthActions.id, input.actionId), eq(growthActions.organizationId, input.organizationId))).limit(1))[0]; if (!action) throw new Error("Acção não encontrada nesta organização."); const progress = Math.max(0, Math.min(100, Math.round(input.progress)));
  const [created] = await db.insert(actionFollowUps).values({ ...input, note: input.note.trim(), progress }).$returningId();
  await db.update(growthActions).set({ progress }).where(and(eq(growthActions.id, input.actionId), eq(growthActions.organizationId, input.organizationId)));
  return { id: created?.id, actionId: input.actionId, progress };
}
export async function listActionFollowUps(organizationId: number, actionId: number) { const db = await getDb(); return db ? db.select().from(actionFollowUps).where(and(eq(actionFollowUps.organizationId, organizationId), eq(actionFollowUps.actionId, actionId))).orderBy(desc(actionFollowUps.createdAt)).limit(30) : []; }
